namespace NServiceBus.Persistence.CosmosDB.SourceGenerator
{
    using System.Text;
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.Text;

    [Generator]
    public class PartitionKeyMappingGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new SyntaxReceiver());
        }

        class SyntaxReceiver : ISyntaxContextReceiver
        {
            public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
            {
            }
        }

        public void Execute(GeneratorExecutionContext context)
        {
            // Short circuit if this is a different syntax receiver
            if (!(context.SyntaxContextReceiver is SyntaxReceiver _))
            {
                return;
            }

            var source =
$@"// <autogenerated/>

class PartitionKeyMapper
{{
    
}}";
            context.AddSource("NServiceBus__PartitionKeyMapper", SourceText.From(source, Encoding.UTF8));
        }
    }
}